<?php

namespace aplicacion\EmisionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenciaRepository extends EntityRepository
{
    public function getAgenciasAsociadasByEmpresa($empresa_id)
    {
        $em=  $this->getEntityManager();
        $empresa= $em->getRepository('BaseBundle:Empresa')->find($empresa_id);
        $agencias= $empresa->getAgencias();
        return $agencias;
    }
    public function blackList($empresa_id)
    {
        $qb=  $this->getEntityManager()->createQueryBuilder();
        $qb2=  $this->getEntityManager()->createQueryBuilder();
    $qb2->select('a.id')
        ->from('EmisionesBundle:Agencia', 'a')
        ->leftJoin('a.empresas', 'e')->andWhere('e.id=:id');
        $qb->select('agencia.id,agencia.nombre')
           ->from('EmisionesBundle:Agencia','agencia')
           ->andWhere($qb->expr()->notIn('agencia.id', $qb2->getDQL()));
        $qb->setParameter('id', $empresa_id);
        return $qb->getQuery()->getArrayResult();
    }
}
