<?php

namespace aplicacion\EmisionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepefectivoTransferenciabancariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepefectivoTransferenciabancariaRepository extends EntityRepository
{
}
