<?php

namespace aplicacion\EmisionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstadoordenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoordenRepository extends EntityRepository
{
}
