<?php

namespace aplicacion\EmisionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PagodirectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagodirectoRepository extends EntityRepository
{
}
