<?php

namespace aplicacion\EmisionesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevisionRepository extends EntityRepository
{
    public function TotalTipo(\DateTime $inicio=null, \DateTime $fin=null,$estado=null, $counter=null)
    {
        //print_r($inicio->format('d-M-Y').'-------'.$fin);exit;
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(revision.id)');
        $qb->from('EmisionesBundle:Revision','revision');
        $qb->andWhere('revision.fecha between :inicio AND :fin');
        if(is_null($inicio))
        {
           $qb->setParameter('inicio', new \DateTime('00:00:00'));
        }
        else
        {
           $qb->setParameter('inicio', $inicio);
        }
        if(is_null($fin))
        {
           $qb->setParameter('fin', new \DateTime('23:59:59'));  
        }
        else
        {
           $qb->setParameter('fin', $fin);  
        }
        if(!is_null($estado))
        {
           $qb->andWhere('revision.estado = :estado');
           $qb->setParameter('estado', $estado); 
        }
        if(!is_null($counter))
        {
           $qb->andWhere('revision.usuario = :counter');
           $qb->setParameter('counter', $counter); 
        }
        return $qb->getQuery()->getSingleScalarResult();
    }
}
