<?php

namespace aplicacion\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
    public function getCountersOrderedByTimeOfQueue($empresa_id,$hora=null)
    {
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u.id, u.username')->from("BaseBundle:User", 'u')->where($qb->expr()->like('u.roles', $qb->expr()->literal("%ROLE_COUNTER%")))
           ->addSelect("(SELECT sum(orden.tiempoProceso)
                FROM EmisionesBundle:Orden orden
                WHERE orden.usuario = u.id and orden.estado=2
                ) AS TC"
                ) 
            ->innerJoin('EmisionesBundle:Usuariointerno', 'ui','WITH','ui.id=u.id')    
            ->andWhere('u.enabled = :enabled')->andWhere('ui.locked=:locked')
            ->andWhere('ui.empresa = :empresa') 
            ->orderBy('TC', 'ASC')
            ->setParameter('empresa', $empresa_id)
            ->setParameter('locked',false)
            ->setParameter('enabled', true);
        if(!is_null($hora))
        {
          $qb->andWhere($qb->expr()->orX(':hora >= ui.inicioJornada and  :hora < ui.inicioAlmuerzo', ':hora > ui.finAlmuerzo and :hora <=ui.finJornada'))
           ->setParameter('hora',$hora/*'15:25:20'*/);       
        }
        
        return $qb->getQuery()->getArrayResult();
    }
}
