<?php

namespace aplicacion\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeriadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeriadoRepository extends EntityRepository
{
    public function loadFeriadosByDate($start,$end)
    {
        $em=  $this->getEntityManager();
        $consulta = $em->createQuery('
        SELECT f.id, f.inicio, f.fin, f.descripcion
        FROM BaseBundle:Feriado f  
        where f.inicio >= :start AND f.fin<=:end
       
       ');
        $consulta->setParameter('start', $start);
        $consulta->setParameter('end', $end);
        return $consulta->getResult();
    }
}
