<?php

namespace aplicacion\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getSubordinados($id)
    {
        $em=  $this->getEntityManager();
        $subordinados=$em->getRepository('BaseBundle:User')->findBy(array('jefe'=>$id));
        return $subordinados;
    }
    public function findByEmail($criteria)
    {
        //print_r('entro');exit;
        return $this
                ->getEntityManager()
                ->createQuery("SELECT u FROM BaseBundle:User u WHERE u.email = :email")
                ->setParameters($criteria)
                ->getResult()
        ;
    }
    public function findByUsername($criteria)
    {
        //print_r('entro');exit;
        return $this
                ->getEntityManager()
                ->createQuery("SELECT u FROM BaseBundle:User u WHERE u.username = :username")
                ->setParameters($criteria)
                ->getResult()
        ;
    }
    public function findByCI($criteria)
    {
        //print_r('entro');exit;
        return $this
                ->getEntityManager()
                ->createQuery("SELECT u FROM BaseBundle:User u WHERE u.ci = :ci")
                ->setParameters($criteria)
                ->getResult()
        ;
    }
    public function availableCounters($estado=null,$empresa=null,$emergencia=false)
    {
         $em=  $this->getEntityManager();
         $qb = $em->createQueryBuilder();
         $qb->select('u')->from("EmisionesBundle:Usuariointerno", 'u')->where($qb->expr()->like('u.roles', $qb->expr()->literal("%ROLE_COUNTER%")));
         if(!is_null($estado))
         {
            $qb->andWhere('u.locked = :lock') ->setParameter('lock',$estado);            
         }
         if(!is_null($empresa))
         {
            $qb->andWhere('u.empresa = :empresa')->setParameter('empresa', $empresa);
         }
         if(!$emergencia)
         {
            $qb->andWhere('u.id != :idemergencia')->setParameter('idemergencia', 701);
         }
        return $qb->getQuery()->getResult();
    }
}
