user:
    path:     /
    defaults: { _controller: "BaseBundle:User:index" }

user_show:
    path:     /{id}/show
    defaults: { _controller: "BaseBundle:User:show" }

user_new:
    path:     /register/
    defaults: { _controller: "BaseBundle:User:new" }

user_create:
    path:     /create/
    defaults: { _controller: "BaseBundle:User:register" }
    requirements: { _method: post }

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "BaseBundle:User:edit" }

user_update:
    path:     /{id}/update
    defaults: { _controller: "BaseBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "BaseBundle:User:delete" }
    requirements: { _method: post|delete }
