
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        # cookie_lifetime tiempo de vida de la session en segundos una semana
        cookie_lifetime: 604800
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                # make sure vendor library location is correct
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../src/aplicacion/AuditoriaBundle/Entity"
                #dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
        dql:
            numeric_functions:
                time_diff: aplicacion\EmisionesBundle\DQL\TimeDiff
        
        

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    encryption: ssl
    auth_mode:  login
    port:       465
    host:      smtp.gmail.com
    username:  emisiones@mymtravel.com
    password:  Emision$$14!
    
    #spool:     { type: memory }
    
#Parametros de configuracion de la aplicacion
parameters:
    aplicacion.directorio.imagenes.usuarios: %kernel.root_dir%/../web/uploads/usuarios/
    aplicacion.directorio.documentos.pdf: %kernel.root_dir%/../web/uploads/pdf/
    aplicacion.directorio.documentos.adjuntos: %kernel.root_dir%/../web/uploads/adjuntos/
    aplicacion.directorio.imagenes.empresas: %kernel.root_dir%/../web/uploads/empresas/
    aplicacion.directorio.imagenes.agencias: %kernel.root_dir%/../web/uploads/agencias/

    
# fos user-bundle
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: aplicacion\BaseBundle\Entity\User
    group:
        group_class: aplicacion\BaseBundle\Entity\Grupo
    
    service:
        mailer: fos_user.mailer.twig_swift
   
    
    registration:
        confirmation:
            enabled:    true 
            template:   FOSUserBundle:Registration:email.txt.twig
        form:
            type: base_user_registration
            name:               fos_user_registration_form
            validation_groups:  [Registration, Default]
            
    profile:
        form:
            type: base_user_profile
            
#Doctrine extension Bundle            
stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:       
        default:
            sortable: true
            loggable: true
               


                
    
                
                
            