#emisiones:
#    resource: "@EmisionesBundle/Controller/"
#    type:     annotation
#    prefix:   /
#
#base:
#    resource: "@BaseBundle/Controller/"
#    type:     annotation
#    prefix:   /

emisiones:
    resource: "@EmisionesBundle/Controller/"
    type:     annotation
    prefix:   /
    
emisionesBundle:
    resource: "@EmisionesBundle/Resources/config/routing.yml"
    prefix: /

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /
    
baseBundle:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix: /

    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile_show:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    
fos_user_profile_edit:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
#no me carga @FOSUserBundle/Resources/config/routing/resetting.xml
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /cambiarclave
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

