
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                default_target_path: /
                always_use_default_target_path: true
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:  
        - { path: ^/cyborg, role: IS_AUTHENTICATED_ANONYMOUSLY }              
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/check-email, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirm, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/confirmed, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/usuariointerno/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/usuariointerno/create, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/agente/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/agente/create, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }         
        - { path: ^/supervisor, role: ROLE_SUPERVISOR }
        - { path: ^/counter, role: [ROLE_COUNTER,ROLE_SUPERVISOR] }
        - { path: ^/queue/manager, role: [ROLE_COUNTER,ROLE_SUPERVISOR,ROLE_CAJA,ROLE_SUPERVISOR_COBRANZA] }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
        
        