ciudad:
    path:     /
    defaults: { _controller: "EmisionesBundle:Ciudad:index" }

ciudad_show:
    path:     /{id}/show
    defaults: { _controller: "EmisionesBundle:Ciudad:show" }

ciudad_new:
    path:     /new
    defaults: { _controller: "EmisionesBundle:Ciudad:new" }

ciudad_create:
    path:     /create
    defaults: { _controller: "EmisionesBundle:Ciudad:create" }
    requirements: { _method: post }

ciudad_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmisionesBundle:Ciudad:edit" }

ciudad_update:
    path:     /{id}/update
    defaults: { _controller: "EmisionesBundle:Ciudad:update" }
    requirements: { _method: post|put }

ciudad_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmisionesBundle:Ciudad:delete" }
    requirements: { _method: post|delete }
