continente:
    path:     /
    defaults: { _controller: "EmisionesBundle:Continente:index" }

continente_show:
    path:     /{id}/show
    defaults: { _controller: "EmisionesBundle:Continente:show" }

continente_new:
    path:     /new
    defaults: { _controller: "EmisionesBundle:Continente:new" }

continente_create:
    path:     /create
    defaults: { _controller: "EmisionesBundle:Continente:create" }
    requirements: { _method: post }

continente_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmisionesBundle:Continente:edit" }

continente_update:
    path:     /{id}/update
    defaults: { _controller: "EmisionesBundle:Continente:update" }
    requirements: { _method: post|put }

continente_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmisionesBundle:Continente:delete" }
    requirements: { _method: post|delete }
