pagodirecto:
    path:     /
    defaults: { _controller: "EmisionesBundle:Pagodirecto:index" }

pagodirecto_show:
    path:     /{id}/show/{orden}/
    defaults: { _controller: "EmisionesBundle:Pagodirecto:show" }

pagodirecto_new:
    path:     /new
    defaults: { _controller: "EmisionesBundle:Pagodirecto:new" }

pagodirecto_create:
    path:     /create
    defaults: { _controller: "EmisionesBundle:Pagodirecto:create" }
    requirements: { _method: post }

pagodirecto_edit:
    path:     /{id}/edit
    defaults: { _controller: "EmisionesBundle:Pagodirecto:edit" }

pagodirecto_update:
    path:     /{id}/update
    defaults: { _controller: "EmisionesBundle:Pagodirecto:update" }
    requirements: { _method: post|put }

pagodirecto_delete:
    path:     /{id}/delete
    defaults: { _controller: "EmisionesBundle:Pagodirecto:delete" }
    requirements: { _method: post|delete }
